name: sleep_sensei_ai
description: A sleep tracking and coaching app powered by AI.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  provider: ^6.1.2
  sensors_plus: ^6.1.1
  flutter_local_notifications: ^19.3.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  uuid: ^4.3.3
  intl: ^0.20.2
  fl_chart: ^1.0.0
  just_audio: ^0.10.4
  timezone: ^0.10.1
  health: ^13.1.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  tflite_flutter: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - .env
